<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.app</groupId>
    <artifactId>banking-application</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>Banking Application</name>
    <description>Banking Microservices Application</description>

    <modules>
        <module>Service-Registry</module>
        <module>API-Gateway</module>
        <module>User-Service</module>
        <module>Account-Service</module>
        <module>Transaction-Service</module>
        <module>Fund-Transfer</module>
        <module>Sequence-Generator</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>